---
- hosts: all
  become: sudo
  tasks:
  
    - name: Installs nginx web server
      apt: 
        name: nginx 
        state: installed 
        
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: 
        name: nginx 
        state: started
