---
- name: Install nginx
  hosts: all
  become: yes
  become_method: sudo
  tasks:
     - name: Download opsramp installer
       shell: curl -X GET -u admin:admin123 http://13.52.130.201:8081/repository/test/ -O 
       
     - name: Updates packages
       debug: msg="{{ result.stdout_lines }}"
