--- 
- 
  become: true
  become_method: sudo
  handlers: 
    - 
      name: "restart apache2"
      service: 
        name: apache2
        state: restarted
  hosts: all
  tasks: 
    - 
      apt: 
        name: apache2
        state: latest
        update_cache: true
      name: "install apache2"
    - 
      apache2_module: "name=rewrite state=present"
      name: "enabled mod_rewrite"
      notify: 
        - "restart apache2"
