---
     - name: Download opsramp installer
       shell: wget --user=admin --password=admin123 http://13.52.130.201:8081/repository/test/install-OpsRamp-Agent.sh -O /home/install-OpsRamp-Agent.sh

     - name: Download deploy agent
       get_url: url=https://s3-us-west-2.amazonaws.com/ath-cfn-configs/public/deployAgent.py dest=/home/ubuntu/ mode=0777 

     - name: Execute the opsramp
       shell: sed -i -e 's/\r$//' install-OpsRamp-Agent.sh
       args:
          chdir: /home/ubuntu
         
     - name: execute
       shell: /home/ubuntu/install-OpsRamp-Agent.sh
       register: result
       args:
         warn: no
         
     - name: Debug
       debug: msg="{{ result.stdout_lines }}"
